### ISSUE TITLE
Cannot run in development during image creation, then in production for deployment

### ISSUE THREAD

**Issue by lincolnthree** [bucharest-gold/centos7-s2i-nodejs#94]
So, it currently seems like there is no way to run in "development" NODE_ENV during a build, then to run in "production" NODE_ENV when the image is actually deployed. 

The BuildConfig NODE_ENV doesn't seem to get picked up.

**Comment by lincolnthree** [comment]
Actually the BuildConfig NODE_ENV doesn't seem to get picked up anyway.

**Comment by lincolnthree** [comment]
```
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'runtime:latest'
          incremental: true
        env:
        - name: "NODE_ENV"
          value: "development"
```

**Comment by lincolnthree** [comment]
I can't seem to get this to use development:

```
---> Installing dependencies
--
  | ---> Using 'npm install -s --only=production'
```

Seems like it should work according to --> https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/env

**Comment by lincolnthree** [comment]
This is what I've tried: 

https://github.com/snowdrop/snowdrop-site-angular/commit/521a89dca5414d939507a1ab9d135bb21765b03a

**Comment by lholmquist** [comment]
Not to long ago i added something to nodeshift to add env vars to your build config,

This is what my build config looks like(edited down)

```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    project: nodejs-rest-http
    provider: nodeshift
    version: 2.0.0
  name: nodejs-rest-http-s2i
  namespace: build-thing
  resourceVersion: '86013'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-rest-http:latest'
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      env:
        - name: NODE_ENV
          value: debug
      from:
        kind: DockerImage
        name: 'bucharestgold/centos7-s2i-nodejs:10.x'
    type: Source
  triggers: []

```

That makes the build phase install dev dependencies.  Looking at where you have your env vars in your build config,  i think they might be in the wrong spot?

I haven't actually tried to do development mode for builds, prod for deploy.  it might work?

**Comment by lholmquist** [comment]
continuing the other comment,

to do developemnt build, production deploy, i guess you would need env vars set for both the build Config and deployment config, but i haven't actually tried that yet.

(looks like i need to also add something to nodeshift to do this, if this is a workflow people need)

**Comment by lincolnthree** [comment]
Looks like yaml is screweing me up.... indentation. Let me try something.

**Comment by lincolnthree** [comment]
Okay, yes, my DC and BC YAML indentation was botched. Adding env: vars here to DeploymentConfig and BuildConfig works as it should. Closing.

**Comment by lincolnthree** [comment]
```
objects:
  - apiVersion: v1
    kind: ImageStream
    ...
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: 'bucharestgold/centos7-s2i-nodejs:10.x'
  - apiVersion: v1
    ...
    spec:
      ...
      strategy:
        type: Source
        sourceStrategy:
          ...
          env:
            - name: "NODE_ENV"
              value: '${NODE_ENV}'
```
